create or replace TABLE COMMON_DB_PRD.CM_ADOBE_TRUSTED_SCHEMA.TF_ADDRESS_ADD (
	ADD_SID_ADDRESS NUMBER(38,0) NOT NULL autoincrement,
	ADD_NUM_I_ADDRESS_ID NUMBER(38,0),
	ADD_NUM_I_DELIVERY_ID NUMBER(38,0),
	ADD_DAT_TS_CREATED TIMESTAMP_NTZ(9),
	ADD_DAT_TS_LAST_ERROR TIMESTAMP_NTZ(9),
	ADD_DAT_TS_LAST_MODIFIED TIMESTAMP_NTZ(9),
	ADD_NUM_I_RECIPIENTS_ID NUMBER(38,0),
	ADD_COD_I_TYPE VARCHAR(16777216),
	ADD_COD_I_STATUS VARCHAR(16777216),
	ADD_COD_I_QUARANTINE_REASON VARCHAR(16777216),
	ADD_COD_S_CRYPTED_EMAIL VARCHAR(16777216),
	ADD_COD_RAW_FILENAME VARCHAR(16777216) NOT NULL,
	ADD_DAT_DLK_CREATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ADD_DAT_DLK_MODIFICATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	ADD_COD_LIB_JOB_NAME VARCHAR(16777216) NOT NULL,
	primary key (ADD_SID_ADDRESS)
);

create or replace TABLE COMMON_DB_PRD.CM_ADOBE_TRUSTED_SCHEMA.TF_AGGREGATES_AGG (
	AGG_SID_AGGREGATES NUMBER(38,0) NOT NULL autoincrement,
	AGG_NUM_I_RECIPIENT_ID NUMBER(38,0),
	AGG_NUM_I_ACTIVE_CUSTOMER NUMBER(38,0),
	AGG_DAT_TS_LAST_EMAIL_CLICK TIMESTAMP_NTZ(9),
	AGG_DAT_TS_LAST_EMAIL_OPEN TIMESTAMP_NTZ(9),
	AGG_COD_S_FIRST_PURCHASE_CHANNEL VARCHAR(16777216),
	AGG_DAT_TS_FIRST_DECLARED_PURCHASE TIMESTAMP_NTZ(9),
	AGG_DAT_TS_FIRST_PURCHASE TIMESTAMP_NTZ(9),
	AGG_DAT_TS_FIRST_REAL_PURCHASE TIMESTAMP_NTZ(9),
	AGG_DAT_TS_LAST_DECLARED_PURCHASE TIMESTAMP_NTZ(9),
	AGG_COD_RAW_FILENAME VARCHAR(16777216) NOT NULL,
	AGG_DAT_DLK_CREATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	AGG_DAT_DLK_MODIFICATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	AGG_COD_LIB_JOB_NAME VARCHAR(16777216) NOT NULL,
	primary key (AGG_SID_AGGREGATES)
);

create or replace TABLE COMMON_DB_PRD.CM_ADOBE_TRUSTED_SCHEMA.TF_BROADLOGEVENTHISTO_BLH (
	BLH_SID_BROADLOGEVENTHISTO NUMBER(38,0) NOT NULL autoincrement,
	BLH_NUM_I_BROAD_LOG_ID NUMBER(38,0),
	BLH_COD_I_FLAGS VARCHAR(16777216),
	BLH_NUM_I_MSG_ID NUMBER(38,0),
	BLH_DAT_TS_EVENT TIMESTAMP_NTZ(9),
	BLH_DAT_TS_LAST_MODIFIED TIMESTAMP_NTZ(9),
	BLH_COD_I_STATUS VARCHAR(16777216),
	BLH_COD_I_DELIVERY_ID VARCHAR(16777216),
	BLH_COD_RAW_FILENAME VARCHAR(16777216) NOT NULL,
	BLH_DAT_DLK_CREATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	BLH_DAT_DLK_MODIFICATION_DATE TIMESTAMP_NTZ(9) NOT NULL,
	BLH_COD_LIB_JOB_NAME VARCHAR(16777216) NOT NULL,
	primary key (BLH_SID_BROADLOGEVENTHISTO)
);
